### ISSUE TITLE
安完 依赖跑步起来

### ISSUE THREAD

**Issue by qinouz** [wuyaoxing/vue-gantt#1]
* ./gantt/codebase/dhtmlxgantt.css in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/gantt/GanttBody2.vue, ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/gantt/GanttBody.vue

**Comment by wuyaoxing** [comment]
@qinouz 更新，代码已重构。
