### ISSUE TITLE
一些有关版本及功能的问题

### ISSUE THREAD

**Issue by NBSeven** [wuyaoxing/vue-gantt#2]
先谢谢你的分享，刚好我在vue项目中用到了你做得组件。看了官网有些疑问，希望大大能帮我解答一下。
1.官网现在是5.+的版本，的确觉得有很多的不同，问一下 4.1 4.2 是不是本来就没有左边的编辑按钮，例如新增task
![image](https://user-images.githubusercontent.com/24637074/38674917-bb85b92c-3e88-11e8-802e-929dd61218c1.png)
2.请问怎么修改时间轴的单位呢（我还在查，还没找到结果），现在默认是年月日，现在想以日和小时做单位（和下图还是有所区别的） 
![image](https://user-images.githubusercontent.com/24637074/38675054-27eab78e-3e89-11e8-9d39-1fd1f3ad5e83.png)

**Comment by wuyaoxing** [comment]
@NBSeven 

1. 可以通过 `gantt.config.columns` 配置。
2. 可以通过 `gantt.config.scale_unit`和`gantt.config.subscales`配置。

相关说明、例子可以参考官方Api和官网示例。

**Comment by NBSeven** [comment]
thanks 已经在看相关配置了
